export type { DomainError, DomainResult } from "./model/result.js";
export { createColor, suggestColor, normalizeCatalogName, catalogNameKey, type Color } from "./model/color.js";
export {
  addRationals,
  compareRationals,
  divideRationals,
  isZero,
  maxRational,
  parseDecimalRational,
  parseSerializedRational,
  rationalFromInteger,
  rationalToCanonicalString,
  subtractRationals,
  type Rational,
} from "./model/rational.js";
export {
  addDays,
  civilDatesInclusive,
  compareCivilDates,
  createCivilDate,
  isoWeekday,
  type CivilDate,
} from "./model/date.js";
export {
  capacityFromSerialized,
  capacityFromRational,
  consumedWorkloadFromSerialized,
  consumedWorkloadFromRational,
  capacityRatioFromSerialized,
  createCapacity,
  createConsumedWorkload,
  createCapacityRatio,
  createDailyCap,
  createMaxParallelProjects,
  createProjectId,
  createProgramId,
  createPriorityFamilyId,
  createRemainingWorkload,
  createReservationId,
  createReservationRatio,
  createTeamId,
  createUnavailabilityRatio,
  dailyCapFromSerialized,
  quantityToDecimalString,
  rationalOf,
  remainingWorkloadFromSerialized,
  reservationRatioFromSerialized,
  unavailabilityRatioFromSerialized,
  serializeQuantity,
  type Capacity,
  type ConsumedWorkload,
  type CapacityRatio,
  type DailyCap,
  type DomainQuantity,
  type MaxParallelProjects,
  type ProjectId,
  type ProgramId,
  type PriorityFamilyId,
  type RemainingWorkload,
  type ReservationId,
  type ReservationRatio,
  type TeamId,
  type UnavailabilityRatio,
} from "./model/scalars.js";
export { createPlanningHorizon, type PlanningHorizon } from "./model/horizon.js";
export {
  createPortfolio,
  effectiveColor,
  createProject,
  createProgram,
  createPriorityFamily,
  createProjectTeamRequirement,
  createTeam,
  type Portfolio,
  type Project,
  type Program,
  type PriorityFamily,
  type ProjectTeamRequirement,
  type Team,
} from "./model/entities.js";
export {
  createCapacityException,
  createCapacityPeriod,
  createTeamCapacitySchedule,
  createWorkingPattern,
  isWorkingDay,
  type CapacityException,
  type CapacityPeriod,
  type IsoWeekday,
  type TeamCapacitySchedule,
  type WorkingPattern,
} from "./capacity/schedule.js";
export {
  createReservation,
  createReservationTeamAllocation,
  isReservationDateApplicable,
  reservationAllocationForTeam,
  type Reservation,
  type ReservationAmount,
  type ReservationTeamAllocation,
} from "./capacity/reservation.js";
export {
  effectiveCapacity,
  isOverReserved,
  projectCapacity,
  reservedCapacity,
  requestedReservationCapacity,
  dailyCapacitySnapshot,
} from "./capacity/calculations.js";
export { planPortfolio } from "./planning/engine.js";
export {
  createProjectActualsChronology, createReservationActualsChronology,
  type ProjectActualsChronology, type ReservationActualsChronology,
  type ProjectActualsRecord, type ReservationActualsRecord,
  type ProjectActualsTeamEntry, type ReservationActualsTeamEntry,
} from "./actuals/records.js";
export { createProjectActualsSnapshot, createReservationActualsSnapshot, createSnapshotHistory, snapshotId,
  type ProjectActualsSnapshot, type ReservationActualsSnapshot, type ActualsCoverage, type ActualsPeriod } from "./actuals/snapshots.js";
export { replaceProjectSnapshot, replaceReservationSnapshot, type SnapshotEvidence, type SnapshotReplacement,
  type SnapshotEditIntent } from "./actuals/transition.js";
export { transitionProjectRequirements } from "./actuals/requirements.js";
export { reconstructActuals, actualOccupationFromReconstruction, type ActualsDailyContribution, type ActualsTeamDayTotal, type ActualsReconstruction } from "./actuals/reconstruction.js";
export type {
  PlanningInput,
  ActualOccupationDay,
  PlanningResult,
  DeadlineStatus,
  PlanningDiagnostic,
  PlanningDiagnosticCode,
  ProjectAllocation,
  ProjectDeadlineStatusByDate,
  ProjectTeamPlanningResult,
  TeamDayAdmission,
  TeamDayCapacity,
  TeamPlanningResult,
} from "./planning/contracts.js";
